In [14]:
# load list of lists into a pandas dataframe
import pandas as pd
 
# initialize list of lists
data = [[1,2,3,4,10], 
        [5,6,7,8,15], 
        [9,10,11,12,20],
       [13,14,15,16,17],
       [18,19,20,21,22]]
 
# Create the pandas DataFrame
df = pd.DataFrame(data)
 
# print dataframe.
print(df)

## count the rows and colums
num_rows = df.shape[0]
num_columns = df.shape[1]

print("num rows " + str(num_rows))
print("num cols " + str(num_columns))

# Iterate through each cell using nested loops
for index, row in df.iterrows():
    for column in df.columns:
        cell_value = df.at[index, column]
        print(cell_value)

## delete dataframe
del df

    0   1   2   3   4
0   1   2   3   4  10
1   5   6   7   8  15
2   9  10  11  12  20
3  13  14  15  16  17
4  18  19  20  21  22
num rows 5
num cols 5
1
2
3
4
10
5
6
7
8
15
9
10
11
12
20
13
14
15
16
17
18
19
20
21
22


In [15]:
## load a list of lists into a two dimensional numpy array
import numpy as np

data = [[1,2,3,4,10], 
        [5,6,7,8,15], 
        [9,10,11,12,20],
       [13,14,15,16,17],
       [18,19,20,21,22]]

# converting list to array
ar = np.asarray(data)

## output the whole 3 dimensional array
print(ar)

rows = ar.shape[0]
cols = ar.shape[1]

print("num rows " + str(rows))
print("num cols " + str(cols))

## iterate through each element
for x in range(0, rows):
    for y in range(0, cols):
        print (ar[x,y])
        
## delete numpy array
del ar

[[ 1  2  3  4 10]
 [ 5  6  7  8 15]
 [ 9 10 11 12 20]
 [13 14 15 16 17]
 [18 19 20 21 22]]
num rows 5
num cols 5
1
2
3
4
10
5
6
7
8
15
9
10
11
12
20
13
14
15
16
17
18
19
20
21
22
